// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XPTOChallenge.Data;

namespace XPTOChallenge.Migrations
{
    [DbContext(typeof(XPTOChallengeContext))]
    partial class XPTOChallengeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("XPTOChallenge.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CNPJClient");

                    b.Property<string>("CPFPrestador");

                    b.Property<DateTime>("dataExecucao");

                    b.Property<string>("nomeCliente");

                    b.Property<string>("nomePrestador");

                    b.Property<string>("tituloServico");

                    b.Property<double>("valorServico");

                    b.HasKey("Id");

                    b.ToTable("OrdemServico");
                });
#pragma warning restore 612, 618
        }
    }
}
